name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          committer_gist: 42365ee9c6c492a7b36bc31f7ec0240f
          base: header
#           plugin_languages: yes
#           plugin_languages_ignored: c, c++, html, css, cmake    
#           plugin_languages_recent_load: 400
          
          plugin_achievements: yes
          plugin_achievements_threshold: A

          plugin_calendar: yes
          plugin_calendar_limit: 6
